### ISSUE TITLE
add loader while data is being fetched.

### ISSUE THREAD

**Issue by NisooJadhav** [NisooJadhav/wikipedia#1]
### The site lives [here](https://wikipedia-nj.vercel.app/).

When the search term is being fetched from Wikipedia API add loader(can be SVG, or CSS loader) below search-box.

[screen-recording.webm](https://user-images.githubusercontent.com/68807845/194072534-0a59be1e-f524-4a28-84c8-798b1c5e6c75.webm)

Steps:
```
1) Fork this repository.
2) Add Loader logic.
3) Commit.
4) Open Pull Request.
```

**Comment by vishnuvnathan** [comment]
Can you assign it to me?

**Comment by rkeshs** [comment]
Still the loader is not appearing

**Comment by NisooJadhav** [comment]
> Still the loader is not appearing

yes, @vishnusnathann can you add a gif if it's working locally?

**Comment by vishnuvnathan** [comment]
Sure @NisooJadhav

**Comment by rkeshs** [comment]
@NisooJadhav it's working locally I've checked
Maybe check with your vercel deploys

**Comment by NisooJadhav** [comment]
> @NisooJadhav it's working locally I've checked Maybe check with your vercel deploys

yes, maybe it's some deployment error

**Comment by NisooJadhav** [comment]
> > @NisooJadhav it's working locally I've checked Maybe check with your vercel deploys
> 
> yes, maybe it's some deployment error

now working [check](https://wikipedia-nj.vercel.app/) thank you @vishnusnathann, @rishikesh2003
